### ISSUE TITLE
Modals

### ISSUE THREAD

**Issue by mdyzma** [alexeyza/startup-programming#27]
Modals as a mai mechanizm to direct logging session (during twitter outh process)

**Comment by alexeyza** [comment]
What does this relate to? a specific file or example?

**Comment by mdyzma** [comment]
Sorry, it was my mistake I pushed wrong issue button.

Cheers.
M

06.07.2017 8:06 PM "Alexey Zagalsky" <notifications@github.com> napisał(a):

**Comment by alexeyza** [comment]
No worries.
