### ISSUE TITLE
mongohq on heroku - can't find free tier

### ISSUE THREAD

**Issue by samnet** [alexeyza/startup-programming#28]
Thanks for the great note, but I have a small issue. 

If I enter 

`heroku addons:add mongohq`

I get:

```
Creating mongohq on ⬢ appIDDDD... $18/month
Created mongohq-reticulated-30930 as MONGOHQ_URL
```

I have entered my billing info into Heroku. My issue is that I can't find (on heroku's website or elsewhere) how to use a free tiered version of `mongohq` add on. Could it be that:
- it does not exist anymore
- it does not exist in my geography? 

Sidenote, this link is dead: http://www.elliotbradbury.com/use-mongohq-heroku-without-verifying-account/.

**Comment by alexeyza** [comment]
Yes, unfortunately I think it's no longer available for free.

**Comment by samnet** [comment]
Works perfectly indeed. 
`heroku addons:add mongolab`.
Thanks.
